env: ras-rm-sandbox
namespace: dev
publicIP: false

gcp:
  project: ras-rm-sandbox
  datastore:
    namespace: dev

image:
  devRepo: eu.gcr.io/ons-rasrmbs-management
  name: banner-api
  tag: latest
  pullPolicy: Always

container:
  port: 8000
service:
  port: 8080

resources:
  requests:
    memory: "400Mi"
    cpu: "150m"
  limits:
    memory: "500Mi"
    cpu: "300m"

autoscaling: false
scaleAt:
  # These are expressed as a percentage of resources.requests, not resources.limits
  memoryPercentage: 130
  cpuPercentage: 500
replicas: 1
maxReplicas: 1
rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1
