env: ras-rm-sandbox
namespace: dev
publicIP: false

replicas: 1
rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

gcp:
  project: ras-rm-sandbox

image:
  devRepo: eu.gcr.io/ons-rasrmbs-management
  name: banner-api
  tag: latest
  pullPolicy: Always

container:
  port: 8000
service:
  port: 8080

resources:
  requests:
    memory: "500Mi"
    cpu: "100m"
  limits:
    memory: "1000Mi"
    cpu: "1000m"