apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: ras-rm-banner
spec:
  selector:
    matchLabels:
      app: ras-rm-banner
  replicas: 10 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: ras-rm-banner
    spec:
      containers:
        - name: ras-rm-banner
          image: eu.gcr.io/ras-rm-sandbox/gcf:latest
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 20
            failureThreshold: 5
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /alive
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 20
            failureThreshold: 5
            successThreshold: 1
            timeoutSeconds: 5
